### ISSUE TITLE
Extra message when removing supplementary content

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#115]
**Current Behavior**: On the production site click the minus button to delete in the supplementary content tab and you get the usual cautionary dialog but then there's a second dialog as well._

**Desired Behavior**: Just the first dialogue, which is as it is on the staging site._

Here's a screenshot of the second dialogue
![image](https://user-images.githubusercontent.com/7329361/38824121-3d1d50ea-4176-11e8-8ce7-693556c105a1.png)

**Comment by ethanbutler** [comment]
@KimPatch – looks like ACF added this as a feature at some point. I just pushed a fix to staging that removes this behavior.

**Comment by ethanbutler** [comment]
Gotcha, thanks for clarifying! It looks like the version of ACF that was on the staging site was out of date, which is why you weren't seeing the second confirmation dialog. I've updated the plugin on staging, so you should be seeing that dialog in both places now. Since it's behavior that's now baked into the plugin, I'd prefer to defer to that style of dialog rather than the one I'd originally implemented.

I'll close this issue out once the recent changes make it to production. Thanks!

**Comment by KimPatch** [comment]
Great – make sense. Thanks!
