### ISSUE TITLE
Interactive page search should match Interview page search

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#135]
Moving this from #97 so we can put this in search 2.0 milestone

 Interactive Pages need to be treated the same in search as Interview Pages.

This will enable users to see hits from the main page search results in interactive blogs. Otherwise the hits won't show up in context on the pages.
Another use for Interactive Pages is for interviews that don't have media, and search needs to be consistent across interviews. 
Interactive Pages can also be used for pages that are longer than blogs. 

I was thinking it makes sense to add the search functionality from the Interviews pages to the similar Interactive pages -search bar the right-hand side of the header, below the picture if there is one. 

This functionality should remain in interactive pages that feed into the blog.

**Comment by ethanbutler** [comment]
Hi Kim – apologies in the delay getting to this one. In implementing this, my concern is that we're reinventing Cmd+F functionality. Any user already has the ability to search the page using the tools natively baked into their browser.

From a technical standpoint, this also presents challenges. As it's implemented currently, the video search is tightly coupled with the existence of a video seekbar. Implementing similar functionality would be roughly the same amount of effort as it was to implement initially, so I don't think this is 

Is there a particular use case you're imagining that isn't supported by Cmd+F?

**Comment by KimPatch** [comment]
@ethanbutler 
This is a matter of keeping the UX consistent and efficient 
1. For regular interviews you click on the hit to go right to that hit in the interview.
But for interviews without media, interactive blog posts, and interactives, when you click on a hit it just takes you to the top of the page, and you have to start the search over again using a different system to continue. 
2. It's also best UX wise if searching the different types of pages on the same site look the same and  involve the same types of controls. Even if you know to switch to the other search system, the inconsistent experience makes it look like something is broken.

Having said all that, if this is significant time, it should go on back burner. 

**Question:** Would be quick to implement passing the search term on to Cmd+F when the user clicks on the returned hit in a search page? If so, this would satisfy 1 and mitigate 2.
If not, can you give me a top-of-your-head ballpark of how much time it would take to implement the similar search functionality and non-Media pages might take? (Feel free to give a range if you don't know off the top of your head – I'm looking for a quick estimate). Then we can put it on the back burner, and maybe get it into maintenance hours in the future.

**Comment by ethanbutler** [comment]
1. The issue here is that, under-the-hood, the "jump to timestamp" feature leverages how Able Player manages the currently-active timestamp, so that videos autoplay from a given point. Without a video on the page, there inherently can't be a currently-active timestamp. Building out this feature for interactive pages that could coexist with the existing functionality would be 4-5 hours.
2. Similarly, the search feature is currently deeply entwined with the Able Player search because of the calculations that go into figuring out where on a timeline terms are. This would be a smaller-scale effort for implement than #1, but would also be a new feature build. I'd estimate that this would be 2-3 hours of build time.

A better solution here (in my opinion) would be to put the effort that would go into this into #63 instead, which could then be used internally. This would be comparable in scope to items 1 and 2 combined, but would be useful in other contexts, too.

**Comment by KimPatch** [comment]
@ethanbutler 
Thanks for the explanations. One clarification on the question above (if you can do so keeping within the maintenance hours) – do you know if it is possible to simply pass the search term on to Command+F functionality of the browser for pages without media?  And if so, do you have a top-of-your-head ballpark for much time that might take to implement?

**Comment by ethanbutler** [comment]
@KimPatch – sure thing. That isn't possible, as that's a feature of the operating system, not the browser.

**Comment by KimPatch** [comment]
Got it – thanks. I'm removing the priority from this one.
