### ISSUE TITLE
Index Bugs

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#169]
- [x] The date on the index page does not always match the interview date on the Interview/Options tab and changing the date on the interviews/options page does not change the date on the index page. The date on the index page should match the interview date on the Interview/Options tab.

- [x] Interviews that are in two different categories don't show up in the second category in the index category view. There are several interviews, including Dean Rusk, that are in both American Diplomats and The Lessons of Crisis  Vietnam and the Cold War.

**Comment by ethanbutler** [comment]
I pushed a hotfix for the first issue, which had to deal with a change that happened at some point in how the datepicker plugin was storing date formats. I'm relabeling this from "bug" to "enhancement" because the case of handling items in multiple categories wasn't discussed prior to the build, and content is still entirely accessible via the Collections page. 

Fixing this involves a partial rewrite of the API response used for the interviews page. I'll have time to implement next month.

**Comment by KimPatch** [comment]
@Ethan Butler – great, sounds good.

**Comment by ethanbutler** [comment]
@KimPatch – just pushed a fix that should resolve the second item.

**Comment by KimPatch** [comment]
@ethanbutler There's something amiss with the fix. I'm looking at the Interviews/Collections View on the staging site expecting to see Ellsworth Bunker appear in two different categories, and there are no categories at all – everything is under standalone interviews.

**Comment by ethanbutler** [comment]
@KimPatch – I'm not experiencing this. Can you clear your browser cache?

**Comment by KimPatch** [comment]
@ethanbutler – Yes – looks good now. Thanks!
