### ISSUE TITLE
Interactive page headline wraps

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#171]
**Current Behavior**: _Interactive page headline wraps too soon._

**Desired Behavior**: _Headline should span the banner._

![image](https://user-images.githubusercontent.com/7329361/44496602-2e9f1f80-a643-11e8-903f-737f54b940e0.png)

**Comment by ethanbutler** [comment]
@KimPatch – this is intentional. The maximum width the title can occupy is 50% because the design assumes that these pages will have a video or featured image to the right. This example looks more extreme because "Transcribing" is a long word.

Changing this would involve a redesign of the header. I'm marking this as wontfix and closing for now.

**Comment by KimPatch** [comment]
@ethanbutler Thanks. Interactive pages never have videos, but they do have the option to add a featured image in the header.  

**Question:** How difficult would it be to have the headline go all the way across if there's not a featured image on an interactive page?

**Comment by KimPatch** [comment]
@ethanbutler looks good – thanks!
