### ISSUE TITLE
Child Theme 

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#176]
@ethanbutler – Moving this from #152 and recapping the relevant details:

Testing making changes to the static portions of the site and site style using the standard WordPress best practice, which is to make a child theme.

I tested this out following the WordPress Codex instructions (https://codex.wordpress.org/Child_Themes). The child theme shows up in Appearance > Themes, but the preview and page source are blank. Is there a special instruction to enqueue styles? If this is the case we need to document this in the README.

Testing details:
I added a child theme directory, rlh-child, in the wp-content > themes directory.
I added functions.php and style.css files in the child directory.

I put the following code in functions.php:

```
<?php
function rlh-child_enqueue_styles() {

    $parent_style = 'rlh-style'; 

    wp_enqueue_style( $parent_style, get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
}
add_action( 'wp_enqueue_scripts', 'rlh-child_enqueue_styles' );
?>
```

I added the following code to style.css:

```
/*
 Theme Name:   RLH Child
 Description:  RLH Child Theme
 Template:     rlh
 Version:      1.0.0
 License:      GNU General Public License v2 or later
 License URI:  http://www.gnu.org/licenses/gpl-2.0.html
 Text Domain:  rlh-child
*/
```

My Result:
The child theme showed up in Appearance > Themes, but the preview was blank and the page source was blank as well.

> Your reply:
> In order for a preview to show up, in Appearance > Themes, a child theme should include a screenshot.png. This is standard WordPress behavior, so I don't think we need to specifically document that. I'm not sure what you're referring to by Page Source. If there's a problem with child theme support, could you open up a separate issue so we can keep this issue focused on documentation?

**Comment by KimPatch** [comment]
@ethanbutler Thanks. Agreed, no need to document standard WordPress behavior. I do think there's an issue with Child Theme support.

I added a screenshot.PNG and the thumbnail for the child theme showed up in Appearance > Themes, but the Child Theme preview is still blank. 

It seems like something might be amiss within enqueuing.
**Question:** does the RLH parent theme functions.php have a wp_enqueue_style() call? Is there something nonstandard about it?

From the [Codex](https://codex.wordpress.org/Child_Themes):
> The correct method of enqueuing the parent theme stylesheet is to add a wp_enqueue_scripts action and use wp_enqueue_style() in your child theme's functions.php.

I used the standard naming convention ($parent_style = 'rlh-style'; ) for calling the parent theme – see above.

**Comment by ethanbutler** [comment]
Hi @KimPatch – I found some issues on my end, as well as some with what you shared. I pushed some changes to the master branch that should make this work. (The issues were with `include` and `require_once` calls for some of the PHP code, including the asset enqueueing, were pointed to the active theme, not necessarily the _parent_ theme.)

From your code – `rlh-child_enqueue_styles` should have an underscore instead of a hyphen. Hyphens in function names in PHP are a fatal syntax error, so your enqueueing code wouldn't run. Also, you don't need to enqueue parent styles – that's already happening in the parent theme. After making these changes, I was able to successfully run the child theme with custom css and a functional screenshot.png with no other changes.

(Note that the production CSS/JS assets aren't bundled in this repo, since I have them set to dynamically build from source code whenever I push to production. I can distribute those to you if need be. There are instructions in the README for building them yourself, as well.)

**Comment by KimPatch** [comment]
@ethanbutler 
Great – thanks. I was going to try this just now but it looks like the code hasn't changed on github yet. 
Thanks for the note about the CSS/JSS assets – if you can put them in the repo with instructions that would be great. We want to do everything we can to make this as easy to try as possible.

**Comment by KimPatch** [comment]
@ethanbutler the child theme enqueueing works now – thanks. Let me know when the production CSS/JS assets are in the repo so I can continue the test.

**Comment by ethanbutler** [comment]
@KimPatch – those files should be in the repo now.

**Comment by KimPatch** [comment]
@ethanbutler Thanks. I took a quick look – it works well now except I get "Undefined" when I click on the Timelines bucket from the homepage and a 404 error when I click on Blog bucket from the homepage.

**Comment by ethanbutler** [comment]
@KimPatch The 404 error was caused because you need to have a Page assigned to the "Blog" template, similar to what we ran into with authors. I added a note to the README about this.

The "Undefined" message was caused because you don't have any published Timelines. I just pushed a change to master that prevent the display of this bucket unless there is actually published content.

Let me know if you run into other issues! Otherwise, you can close this ticket once you've had a chance to review.

**Comment by KimPatch** [comment]
Great – thanks!
