### ISSUE TITLE
Link behavior

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#42]
We are aiming to improve the user experience in clicking links within an interactive transcript. 

Here’s a sample with a bunch of links:
http://rlhdemo.sanford.duke.edu/interviews/2018-01-08-pr-test/ 

When the user clicks on one of the blue links the linked page currently opens in the same window, meaning the user has to use the back button to go back and forth. But if we had the link open in a new tab I’m not sure that that would work well either because the user might get lots of redundant tabs open because a lot of the links are to different places in the same interview. Is it possible to open the link in a new tab unless that link is already open, and if that’s the case to send the user to the new location in the open tab? Other thoughts?

**Comment by ethanbutler** [comment]
@KimPatch: that's not going to be possible due to security restrictions put in place by browsers – tabs are "sandboxed" from each other, or else one site might have access to confidential content in another site that it shouldn't. I'll revise this so that links open in new tabs and users can sort their tabs based on their specific use-case.
