### ISSUE TITLE
Sentence-level URLs for text not connected to media

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#43]
Enable text that’s not connected to audio or video to be selected with a URL at the sentence level. This would enable transcripts without media in a similar way to the media transcripts. 

1. I think the simplest way to do this within the site is to give the user a way to automatically add dummy time codes in the .vtt window. The codes would need to be added on a new line anywhere there is a blank line (ignoring NOTE). This would enable this for our site in a nice simple way that would be easy for the content providers.

2. The goal here is to have a URL that points directly to a sentence in text just like  we have with text connected to video. So in addition to doing this on the Duke site we'd also like a way for others to enable their stories down to the sentence level  so we can point to them. What would it take to do a WordPress plug-in that would enable this on an existing site? Other thoughts?

**Comment by KimPatch** [comment]
Note: this is also related to #63 #66 and #78

**Comment by KimPatch** [comment]
My last thought from #63: 
> Note: No-media interactive pages enables pointing at the sentence level. Hypothes.is is open source software that uses an annotation scheme to do this – this may give content creators this ability without us doing any development. 

I'm also thinking that enabling sentence-level URLs anywhere really belongs at the WordPress core level. Also repeating from #66 that this is low priority.

**Comment by ethanbutler** [comment]
@KimPatch - in the WordPress philosophy, this functionality belongs in a plugin. There is specific HTML markup needed to implement something like this, so it's not "core" functionality since it would (likely) negatively affect users who don't want it. This is why plugins exist – so that users can opt-in to behavior.

I'm happy to privately provide estimates for implementing this feature as a plugin, so I'll leave this issue open to discuss this feature. This is the route I would advocate for instead of continuing to put project budget towards the HTML-to-WebVTT-to-HTML approach you're pushing for in other issues. It would be significantly more feasible to handle this with a separate piece of client-side JS that could be packaged as a plugin, or distributed for use on other non-WordPress sites.

**Comment by KimPatch** [comment]
@ethanbutler I think we're talking about two different things regarding item 2 above – my question  about a WordPress plug-in. I'm talking about a WordPress ability that would automatically number sentences so content could be accessed at the sentence level rather than just at the page level. This would enable people to connect to and share particular sentences of content. I think it might be better if something like this was core functionality. It would be quicker to do it as a plug-in, though. Ideally, I don't see this affecting users – it's not something that content creators should have to do much if anything to implement. 

In #66, which enabled Item 1 above, we also talked about Item 2, and you mentioned WordPress short codes or markdown. This would be additional work for the content creators and would make the files hard to read – instead, we want to do one simple thing – number sentences – automatically. 

In #177 we're working out the logic of numbering sentences for the purpose of enabling Interactive interviews that are connected to media and Interactive pages for the Duke theme. This is related and might prove useful in enabling WordPress functionality that enables sentence-level URLs.
