### ISSUE TITLE
Tablet  copy 

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#45]
on the tablet view staging site – this one also shows up on the Duke site:
When I select, then click the Facebook/Twitter/copy icon to copy and then paste I get just the first word of the selection. I expect to get the whole selection and the direct URL, but I get just the first word of the selection and the direct URL.
(Note that this is the case only in tablet view, phone view is fine)

**Comment by KimPatch** [comment]
Testing after you pushed the fix for code that normalizes the share dialog for iOS that wasn’t targeting tablet sizes:
The tablet issue is still there (only one word of the quote copy) and now the Apple copy/lookup/share dialogue is coming up partially over the Duke share this dialog, and sometimes this obscures the selection indicator. A couple of examples:
![tablet copy issue-1](https://user-images.githubusercontent.com/7329361/36575287-3aeba11e-1818-11e8-8990-3e19f047a69e.jpeg)
![tablet copy issue-2](https://user-images.githubusercontent.com/7329361/36575305-50d2da9c-1818-11e8-9c8a-083154b804bf.jpg)

**Comment by ethanbutler** [comment]
@KimPatch – when I'm working on this later today I'm going to roll back that change, to fix the buggy positioning. After I do so, what would be helpful would be for you to take a screenshot right before you hit the share button.

Can you also verify you're running the latest iOS and Safari? I'm testing this on an iPhone, but I can't imagine there would be differences in the text selection API across different devices running the same OS.

**Comment by ethanbutler** [comment]
After spending a few minutes looking at the source code for how share links on the site work, this seems like an area that would benefit from some refactoring, as there were similar issues in #41. I'm going to spend some time thinking about how best to restructure this.

**Comment by ethanbutler** [comment]
@KimPatch – I completely overhauled the way that site search worked. Previously, highlighting worked by adding the share link element to the page, and then updating an HTML data attribute on that element whenever the highlight changes. While it's rare that issues happened, there was definitely the possible for cases where sharing actions would be triggered before the right thing in the right place was updated.

I refactored this by making it so that whenever the selection changes, the share links are completely redrawn. This should make links responsive to absolutely any change in selection.

**Comment by KimPatch** [comment]
Great. This is better – it's easy to select and responsive. But there's still an overlap between the Apple share element and the Duke share element. It's really tricky to press the Duke element with the Apple Share element overlapping. Sometimes you press once and the Apple Share element goes away and then you can press again. Sometimes you press again and everything goes away and it doesn't copy.

When I select the Duke element stays at the top of the selection and then the Apple element appears at the top and overlaps. This is the case whether I select up or down. Is there any way to get the Duke element to appear below the selection rather than above it?

![file feb 28 5 37 07 pm](https://user-images.githubusercontent.com/7329361/36817251-732027ae-1cae-11e8-965c-a237728bcc94.jpeg)

**Comment by ethanbutler** [comment]
@KimPatch – I've pushed a fix for this. It seems that the re-rendering functionality here was a bit overzealous – it would remove the sharing element if the text selection was empty, and the act of clicking the icons would oftentimes trigger a new selection.

For the positioning: I've amended this so that below-text is the default position, _unless_ a user isn't using a touch device **and** the bottom of the selection is very close to the bottom of the viewport.

**Comment by KimPatch** [comment]
Selecting now looks great on all three platforms. I think this broke something, though – supporting content is now all open on all platforms even though the open by default boxes are not checked on the backend. For instance, look at http://rlh.demo.sqnts.xyz/interviews/joel-fleishman/. There's also an odd artifact in the Karen Tumulty interview, which has no supporting content – I suspect this is related.

![artifact mar 01 12 53 58 pm](https://user-images.githubusercontent.com/7329361/36861356-a298189a-1d51-11e8-993c-122ec0fd1e12.jpeg)

**Comment by ethanbutler** [comment]
This should be resolved – looks like a fix for highlighting supporting content text was causing everything to be expanded during the check.

**Comment by KimPatch** [comment]
great – looks good!
