### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#51]
**Current Behavior**: Period (.) interpreted as any character in search

**Desired Behavior**: Period interpreted as just a Period in search.

**Other details:** To test, Search for "U.S." – You'll see that it highlights instances of "U" followed by anything and "S" followed by anything.

**Comment by KimPatch** [comment]
The bug is still there – the instances that are letters rather than periods don't show up in the seek bar, but they are highlighted in the text (Chrome and Firefox).

**Comment by ethanbutler** [comment]
@KimPatch – could you give me an example of a word you're seeing highlighted? I noticed this was affecting the word "ourselves" and I'm not seeing it there anymore.

(A little about what was/is happening under the hood: the full search term gets converted to a regular expression, where a `.` character is a wildcard – so anything in one word that has a `u` followed by an `s` gets caught. I attempted to fixed this by escaping the search term so that special characters get escaped.)

**Comment by KimPatch** [comment]
Thanks for the explanation. It seems like the periods are acting as wildcards still. Here's an example – note the one proper hit of U.S.  shows in the seek bar.

![image](https://user-images.githubusercontent.com/7329361/36756487-1c8dcbe8-1bdd-11e8-8c3d-8a3fa2f0ac84.png)

**Comment by ethanbutler** [comment]
Gotcha, thanks! I was looking at the search results page.

Leaving [this](https://www.npmjs.com/package/escape-string-regexp) here for myself.

**Comment by ethanbutler** [comment]
@KimPatch – I've pushed a fix for this.

**Comment by KimPatch** [comment]
Highlights are now correct in the text of the interview – great. The proper supporting content still opens, but there are no highlights in the supporting content. 

Question: what would it take to add "Whole Word Only" and "Match Case" checkbox options as checkbox items on a drop-down beside the search icon.  Use case: search for "hate", for instance.

**Comment by ethanbutler** [comment]
@KimPatch – I just pushed a fix for the highlighting behavior. I'm going to open a new issue for your question, as it's a separate matter. Could you mark this as accepted when you've had a chance to review?

**Comment by KimPatch** [comment]
Looks great – thanks.
