### ISSUE TITLE
Add search parameters

### ISSUE THREAD

**Issue by ethanbutler** [DukeLivingHistory/RLH-Site-Code#54]
**Current Behavior**: Search matches any instance of a sequence of characters, regardless of if matches that "word."

**Desired Behavior**: Add options for matching whole words only, or matching exact case.

**Questions:** Would it make the most sense to display these options in the navbar, or as options on the search results page itself? 

***

* For bugs, please add the "Bug" label 
* For feature requests, please add the "Enhancements" label
* For general questions, add the "Questions" label
* When changes are satisfactory, please add the "Accepted" label to mark that changes are ready to push to production

**Comment by ethanbutler** [comment]
@KimPatch – in my opinion, the best option here would be to display the options on the search results page. I don't think there's enough room in the nav to include both checkboxes and labels. I'm thinking the best way for this to look would be to stick the UI for this right next to the "Total hits" heading, similar to what I did for the "Expand All" button.

(Also, I'm marking this with a milestone of Revised Search 2.0. This might end up being complicated from a UI standpoint, and I'd prefer not to delay pushing the search to production.)

**Comment by KimPatch** [comment]
Understood about 2.0.

Thinking this through I think if we included this on the search page there are a couple of minuses: The user would perhaps have to do a second action to get the search right, and then a user were to put in a second search term and need a different refinement the user would be accessing controls that are in two different places. I was picturing a triangle drop-down next to the magnifying glass, and I think this would be simpler for the user to both discover and use. 

Question for you is what are our options for search? If you were to put a drop-down next to the magnifying glass on the main search and collection search controls, is there a standard set? Would it be easy to include a wildcard or even regular expressions?

**Comment by ethanbutler** [comment]
@KimPatch – applying wildcard and regex searches is possible, but would be a high-effort tasks since we would essentially need to rewrite the underlying database query for the WordPress search to use REGEXP instead of LIKE, which is a significant hurdle. This would dramatically slow down queries, so we'd also need to build out a separate API endpoint so "regular" searches wouldn't be impacted. Finally, we'd also need to build all these new queries in a way that they can all work together if combined, as well as to build out the UI.

(For whole-word searches, it looks like we'd also need to [reimplement the SQL to use Regex.](https://stackoverflow.com/questions/656951/search-for-whole-word-match-in-mysql).)

I understand the rationale behind whole-word searches, but could you walk me through the use case for regex/wildcard searches? I want to loop the rest of the team in on this so that we can make sure this is a task that's worth the effort. I can provide an estimate privately, if needed.

- [ ] Wildcard support
- [ ] Regex
- [ ] Controls for chonological order (from #133)
- [ ] Controls for title order (from #133)

**Comment by KimPatch** [comment]
Thanks for laying this out. Understood that regex isn't the right tool here.  I was thinking that it might be relatively easy to implement and would get us a lot of functionality. But it sounds like there are a bunch of issues. So the question is what are the good options for more sophisticated search? 
- Whole-word search is most important. 
- Match case is also very useful. 
- It would be useful to be able to search for numbers, but it looks like the engine won't return a search that's shorter than four characters. 
- Boolean search terms would be very useful.
- I can include periods and commas in a search term, but not quote marks – it would be useful if quote marks could be included.
**Question:** Are there practical options for just the first two, or for a combination of the first two and any of the others?

**Comment by KimPatch** [comment]
@ethanbutler forgot to @ you in the above comment

**Comment by ethanbutler** [comment]
@KimPatch – I'll be able to implement whole-word and case match search over the weekend. I can also revise the search to remove the four-letter requirement. 

The issue with quotation marks seems to be that content in transcripts largely (if not entirely) uses smart quotes (“) and searches use regular quotes ("). I'll look into this and see if there's an easy way to fudge the DB query to match either, but if not, this might be a case of needing to update the content or a limitation of what we'll be able to do.

Could you explain the boolean search term?

**Comment by KimPatch** [comment]
@ethanbutler 
Great!

Most search engines support Boolean searching by allowing users to put search terms in quotes if they want them to be exact, and otherwise doing an OR search. But the exact phrase search is already the default on the Rutherfurd site, as it should be, and we want users to be able to search for punctuation. So it would make the most sense for to distinguish the existing exact phrase search from AND and OR as drop-down choices: exact phrase/any of these words/all of these words, with exact phrase remaining the default. (The wording is similar to Google Advanced Search, so should be familiar to folks, especially researchers.)

**Comment by KimPatch** [comment]
Thanks for the details. Let’s go with plan A — at least for now — just the whole word, case match and remove the 4-letter requirement, which will enable searching for numbers.

**Comment by ethanbutler** [comment]
This is on staging!

**Comment by KimPatch** [comment]
@ethanbutler 
Great  – the interface generally looks good,
- [ ] but would be better if  the text were the same size as the menu items, which would make it easier to see and the checkbox easier to use. 
- [ ] And it would be better if the choices were stacked. 
And the functionality looks good except
it looks like it's not fully implemented. When I search on State, for instance, I get the same number of hits whether the boxes are checked or not, but some of the interviews have no highlighted hits.  So it looks like what's happening when the boxes are checked is the highlighting is correct – just "State" is highlighted and not "state" and "stated", but
- [ ] the interviews that contain only terms like state and stated still show up with no highlighting, but shouldn't show up at all
- [ ] and the hit count is also counting all forms instead of just the whole words capitalized hits
