### ISSUE TITLE
Revised Blog Homepage

### ISSUE THREAD

**Issue by ethanbutler** [DukeLivingHistory/RLH-Site-Code#72]
- [x] Modeled on front page of site
- [x] Posts should have different icon and color
- [x] Same reordering functionality

**Comment by KimPatch** [comment]
Some clarification:
- [ ] The blog homepage should be modeled on the current front page, with featured item, three boxes, then eight boxes (we are going to take the eight boxes of the current homepage, but want them on the blog homepage).
- [ ] The blog boxes should also have bylines.
Question: Given that we need the ability to sort by author anyway, can we make these bylines show up automatically rather than including them in the description  text?

**Comment by KimPatch** [comment]
There are related comments in #73

**Comment by KimPatch** [comment]
@ethanbutler It looks like the fix truncated the picture:

![image](https://user-images.githubusercontent.com/7329361/38498646-192bd6c8-3bd3-11e8-9fa5-89076ea37eaf.png)

**Comment by KimPatch** [comment]
@ethanbutler Also missing is a way to put an interactive page into the blog feed. (Here's a test page for this.
http://rlh.demo.sqnts.xyz/wp-admin/post.php?post=2285&action=edit)

I'm picturing an "Include in blog feed" checkbox on the interactive page entry in the backend

**Comment by KimPatch** [comment]
Two other items:
[ ] What Katie mentioned – The menu item is going to remain blog, but we need the "blog" in the upper right-hand corner to be the name of the blog. Can we add a control on the options page for this so the content creators can control this?
[ ] The 8 extra boxes toggle checkbox works for the homepage, but the one in the blog options area has no effect. I check it, save the options page, reload the blog page and the extra eight boxes do not appear.

**Comment by ethanbutler** [comment]
@KimPatch I've added the above functionality – there's now a blog title field and a checkbox on interactives to enable hiding them from the blog feed.

One note – the toggle to hide the feed on the blog homepage works fine for me. I just want to make sure that you're using the checkbox in the "Blog Settings" metabox and not the "Home Settings".

**Comment by KimPatch** [comment]
@ethanbutler 
Always good to check – I'm using the checkbox on blog settings:
![image](https://user-images.githubusercontent.com/7329361/38557929-9f9e8574-3c9c-11e8-8414-561bdb881c3f.png)

Updating, and this is what I see –
also, the Explanatory text about Rutherford is missing.
 ![image](https://user-images.githubusercontent.com/7329361/38557827-43f8e200-3c9c-11e8-9365-3efe78529bb3.png)

**Comment by KimPatch** [comment]
I'm not seeing a title field for the blog in Options, or the checkbox in Interactive pages. I think these somehow didn't get all the way through.

**Comment by ethanbutler** [comment]
Apologies – there was a deployment error I didn't catch. This should be correct now.

**Comment by KimPatch** [comment]
@EthanButler 
Great – I'm seeing the title field and the title to hide the 8 boxes works.
Thanks for fixing the picture – one more glitch on that page:
[ ] The View Post button on the blog on the very top does not respond.
I also see the checkbox on interactive pages. 
[ ] Can we make the checkbox opt in rather than opt out? "Show in blog"
[ ] The content creator also needs to be able to choose to put the Interactive Pages that are opted in on the front of the blog homepage. Can those be added to the dropdown in blog options?
[ ] When the interactive pages appear on the blog homepage they should appear the same as the blog, with date and author name and the first bit of text. 
[ ] The opted in interactive should also appear in the author feeds for the blog.

**Comment by ethanbutler** [comment]
@KimPatch – the above feedback should be addressed.

**Comment by KimPatch** [comment]
Thanks! The View Post link on the blog now responds
[ ]  but the View Interactive link does not respond.
[ ] I'm not seeing the change in the checkbox opt in
![image](https://user-images.githubusercontent.com/7329361/38673607-cc05ce5e-3e1f-11e8-9698-ea6fe5a93f11.png)
Thanks for adding interactive pages to blog options – that looks great!
interactive pages on the blog homepage has date and author name
[ ] but is still lacking the first bit of text
The interactive page shows on the blog homepage and author feeds – great!

**Comment by ethanbutler** [comment]
@KimPatch The above items should be fixed, with two notes:

- For interactive page excerpts, you'll need to use the "Excerpt" field, just like on interviews and timelines. If you don't see this, click Screen Options and check the checkbox next to it.
- By switching to _show_ in blog rather than _hide_ in blog for interactives, all previously published interactives are now visible in the blog because they don't explicitly have a `show_in_blog` record in the database set to false. The blog logic checks for posts or interactives with `show_in_blog` set to true  OR `show_in_blog` not set at all. (Otherwise, posts wouldn't appear since they don't have this record). If you re-save an interactive with no changes, it will update the record and behave as expected. Just wanted to give you a heads-up so you don't think this is a bug. (This is why I'd made the decision to use `hide_in_blog` initially. Previously the logic was `hide_from_blog` NOT false OR `hide_from_blog` not set at all, which worked with existing content).

**Comment by KimPatch** [comment]
@ethanbutler 
Thanks, and thanks for the notes. This all makes sense. 
I've switched all the posts, and everything looks good. 
I'm seeing the explanatory text on the blog homepage.
And the excerpt field makes sense as well – great.
[ ] One small request – now that I see these I think all the post links, including interactive should be "View Post" – the interactive box is different enough anyway, and it's cleaner using the shorter name for all of them. Thanks much for your patience on this.

**Comment by KimPatch** [comment]
Thanks!
