### ISSUE TITLE
Add Timelines to Collection page

### ISSUE THREAD

**Issue by ethanbutler** [DukeLivingHistory/RLH-Site-Code#74]
Eliminate timelines homepage.

The two types of entries would appear interspersed in alphabetical order and if a Collections entry and Timelines entry have the same name, the collections entry would come first

**Comment by KimPatch** [comment]
One clarification: we want to keep the Timelines homepage, but have Timelines **also** feed into the collections page.****

**Comment by KimPatch** [comment]
Shoot. There was something we didn't think about here. The Collection and related Timeline can have a different name. In this case, the "Civil Rights…" Timeline goes with the "Closing the Polls…" collection and should fall after it, but the names are the same and alphabetically it turns out the opposite way. Looking at this I think we need some way of associating a timeline with a collection, or maybe it would be simpler to have a collections sort field (beside the Hide from Collections field) that automatically puts the name of the Timeline in, but the content creator can change it to the associated Collection name. What you think?

**Comment by KimPatch** [comment]
Yes – this looks great. And yes, if the timeline were associated with multiple collections it should appear in every collection.

**Comment by ethanbutler** [comment]
@KimPatch – this is up on staging.

**Comment by KimPatch** [comment]
This looks great – thanks.

**Comment by KimPatch** [comment]
Thanks!
