### ISSUE TITLE
Excerpt cutoff length on front page and interview pages

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#76]
**Current Behavior**: _Interview Excerpt is cut off on the featured spot on the front page and on the Interview pages._

**Desired Behavior**: _Expect text to be cut off based on space._

**Other details:** There seems to be more room on the front page to let the excerpts be little longer. See where this one is cut off:
![image](https://user-images.githubusercontent.com/7329361/37361561-971c7d9a-26c9-11e8-8e52-c46a41d17224.png)
Can we allow the featured excerpt to go longer?

Also, this one is oddly cut off in the interview page – I expect the  cut off and ellipsis to come near the end of the line, but there's lots more room on the line (regardless of how I size the window):
![image](https://user-images.githubusercontent.com/7329361/37361738-fd5123ea-26c9-11e8-95aa-1f00fa03b21e.png)

**Comment by ethanbutler** [comment]
@KimPatch The cutoff is based on word count, not on available size. I'm retagging this as an enhancement so that we can revisit this in the future.

**Comment by KimPatch** [comment]
Can you for now increase the word count by 20 or 12?

**Comment by ethanbutler** [comment]
@KimPatch – I've set the word length to 80 for the time being, which should display the full excerpt for all of the content on the site. The reason I did this rather than just using the full excerpt is that the "Closing The Polls" collection on the production site has a comparatively really long description provided.
