### ISSUE TITLE
Homepage links

### ISSUE THREAD

**Issue by KimPatch** [DukeLivingHistory/RLH-Site-Code#99]
**Current Behavior**: The links on the site homepage above the description boxes are not correct and are affected by the content role checkbox.

**Desired Behavior**: The links on the site homepage above the description boxes should remain stable and not be affected by the content role checkbox.

**Other details:** On the site home page, there were at first no text on the links (at this point I had tested the homepage content role checkbox)
![image](https://user-images.githubusercontent.com/7329361/38503120-350b0010-3bdf-11e8-885c-d2670f603e0d.png)

Then when I tested the **blog** content role by checking the content role checkbox in the blog options section, the text on the site homepage links changed to the blog entries. Now it stays this way – it's not further affected by the checkboxes.
![image](https://user-images.githubusercontent.com/7329361/38503377-ea1256b6-3bdf-11e8-946b-98055744489d.png)

Here's the original – this is the way the links should remain:
![image](https://user-images.githubusercontent.com/7329361/38507205-eb916bc6-3be9-11e8-988d-cf32a5aa471d.png)

**Comment by ethanbutler** [comment]
What happened here is that I pushed a change that moves the Advanced Custom Fields schema out of the WordPress UI and into the codebase, so that I don't have to change that manually when running deployments. It looks like this field didn't migrate smoothly. I fixed the links for you. Leaving this open so that when the most recent changes get deployed to production I can fix it there too.

**Comment by KimPatch** [comment]
@ethanbutler – also needs to be fixed on the rlh demo site
